In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("C:/Users/Srik3/OneDrive/Documents/DA OR DS Projects/matches.csv", index_col = 0)

In [3]:
matches.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,Match Report,NaN,18.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,Match Report,NaN,16.0,4.0,18.5,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,Match Report,NaN,25.0,10.0,14.8,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,Match Report,NaN,25.0,8.0,14.3,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,Match Report,NaN,16.0,1.0,16.4,1.0,0.0,0.0,2022,Manchester City

In [4]:
matches.shape

(1520, 27)

In [5]:
matches['Team'].value_counts()

Manchester City             76
Liverpool                   76
Watford                     76
Burnley                     76
Leeds United                76
Everton                     76
Southampton                 76
Aston Villa                 76
Brentford                   76
Crystal Palace              76
Newcastle United            76
Wolverhampton Wanderers     76
Brighton and Hove Albion    76
Leicester City              76
West Ham United             76
Manchester United           76
Arsenal                     76
Tottenham Hotspur           76
Chelsea                     76
Norwich City                76
Name: Team, dtype: int64

In [6]:
matches.isna().sum()

Date               0
Time               0
Comp               0
Round              0
Day                0
Venue              0
Result             0
GF                 0
GA                 0
Opponent           0
xG                 0
xGA                0
Poss               0
Attendance         0
Captain            0
Formation          0
Referee            0
Match Report       0
Notes           1520
Sh                 0
SoT                0
Dist               0
FK                 0
PK                 0
PKatt              0
Season             0
Team               0
dtype: int64

In [7]:
matches[matches['Team'] == 'Liverpool']

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
0,2021-08-14,17:30,Premier League,Matchweek 1,Sat,Away,W,3,0,Norwich City,...,Match Report,NaN,19.0,6.0,17.3,1.0,0.0,0.0,2022,Liverpool
1,2021-08-21,12:30,Premier League,Matchweek 2,Sat,Home,W,2,0,Burnley,...,Match Report,NaN,27.0,8.0,16.1,0.0,0.0,0.0,2022,Liverpool
2,2021-08-28,17:30,Premier League,Matchweek 3,Sat,Home,D,1,1,Chelsea,...,Match Report,NaN,23.0,6.0,16.2,0.0,1.0,1.0,2022,Liverpool
3,2021-09-12,16:30,Premier League,Matchweek 4,Sun,Away,W,3,0,Leeds United,...,Match Report,NaN,30.0,8.0,16.1,1.0,0.0,0.0,2022,Liverpool
5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,W,3,0,Crystal Palace,...,Match Report,NaN,25.0,10.0,16.4,1.0,0.0,0.0,2022,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,2022-04-30,12:30,Premier League,Matchweek 35,Sat,Away,W,1,0,Newcastle Utd,...,Match Report,NaN,24.0,10.0,17.7,2.0,0.0,0.0,2021,Liverpool
57,2022-05-07,19:45,Premier League,Matchweek 36,Sat,Home,D,1,1,Tottenham,...,Match Report,NaN,22.0,3.0,19.6,1.0,0.0,0.0,2021,Liverpool
58,2022-05-10,20:00,Premier League,Matchweek 33,Tue,Away,W,2,1,Aston Villa,...,Match Report,NaN,17.0,5.0,17.0,2.0,0.0,0.0,2021,Liverpool
60,2022-05-17,19:45,Premier League,Matchweek 37,Tue,Away,W,2,1,Southampton,...,Match Report,NaN,24.0,5.0,18.6,0.0,0.0,0.0,2021,Liverpool
61,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3,1,Wolves,...,Match Report,NaN,29.0,7.0,15.6,0.0,0.0,0.0,2021,Liverpool

In [8]:
matches.dtypes

Date             object
Time             object
Comp             object
Round            object
Day              object
Venue            object
Result           object
GF                int64
GA                int64
Opponent         object
xG              float64
xGA             float64
Poss            float64
Attendance      float64
Captain          object
Formation        object
Referee          object
Match Report     object
Notes           float64
Sh              float64
SoT             float64
Dist            float64
FK              float64
PK              float64
PKatt           float64
Season            int64
Team             object
dtype: object

In [9]:
del matches['Notes']

In [10]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Referee,Match Report,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,Anthony Taylor,Match Report,18.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,Graham Scott,Match Report,16.0,4.0,18.5,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,Martin Atkinson,Match Report,25.0,10.0,14.8,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,Paul Tierney,Match Report,25.0,8.0,14.3,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,Jonathan Moss,Match Report,16.0,1.0,16.4,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,John Brooks,Match Report,9.0,3.0,21.6,0.0,0.0,0.0,2021,Norwich City
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,Robert Jones,Match Report,8.0,2.0,22.2,1.0,0.0,0.0,2021,Norwich City
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,Simon Hooper,Match Report,9.0,5.0,17.0,0.0,0.0,0.0,2021,Norwich City
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,Tony Harrington,Match Report,11.0,2.0,14.4,0.0,0.0,0.0,2021,Norwich City
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,Chris Kavanagh,Match Report,9.0,0.0,18.6,0.0,0.0,0.0,2021,Norwich City

In [11]:
#convert existing column to datetime
matches["Date"] = pd.to_datetime(matches["Date"])

In [12]:
matches.dtypes

Date            datetime64[ns]
Time                    object
Comp                    object
Round                   object
Day                     object
Venue                   object
Result                  object
GF                       int64
GA                       int64
Opponent                object
xG                     float64
xGA                    float64
Poss                   float64
Attendance             float64
Captain                 object
Formation               object
Referee                 object
Match Report            object
Sh                     float64
SoT                    float64
Dist                   float64
FK                     float64
PK                     float64
PKatt                  float64
Season                   int64
Team                    object
dtype: object

In [13]:
def to_num(result):
    if result == 'W':
        return int(1)
    else:
        return int(0)

In [14]:
matches['Target'] = matches['Result'].apply(to_num)

In [15]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Sh,SoT,Dist,FK,PK,PKatt,Season,Team,Target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,Match Report,18.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,Match Report,16.0,4.0,18.5,1.0,0.0,0.0,2022,Manchester City,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,Match Report,25.0,10.0,14.8,0.0,0.0,0.0,2022,Manchester City,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,Match Report,25.0,8.0,14.3,0.0,0.0,0.0,2022,Manchester City,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,Match Report,16.0,1.0,16.4,1.0,0.0,0.0,2022,Manchester City,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,Match Report,9.0,3.0,21.6,0.0,0.0,0.0,2021,Norwich City,0
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,Match Report,8.0,2.0,22.2,1.0,0.0,0.0,2021,Norwich City,0
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,Match Report,9.0,5.0,17.0,0.0,0.0,0.0,2021,Norwich City,0
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,Match Report,11.0,2.0,14.4,0.0,0.0,0.0,2021,Norwich City,0
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,Match Report,9.0,0.0,18.6,0.0,0.0,0.0,2021,Norwich City,0

In [16]:
def ven(code):
    if code == 'Away':
        return 0
    elif code == 'Home':
        return 1

In [17]:
def opp(code):
    if code == 'Away':
        return 0
    elif code == 'Home':
        return 1

In [18]:
#conversion to categorical data type in pd
#converting string into categories and then converting those categories into numbers
matches["Venue_Code"] = matches["Venue"].astype("category").cat.codes
#matches["Venue_Code"] = matches["Venue"].apply(ven)

In [19]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Sh,SoT,Dist,FK,PK,PKatt,Season,Team,Target,Venue_Code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,18.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,0,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,16.0,4.0,18.5,1.0,0.0,0.0,2022,Manchester City,1,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,25.0,10.0,14.8,0.0,0.0,0.0,2022,Manchester City,1,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,25.0,8.0,14.3,0.0,0.0,0.0,2022,Manchester City,1,0
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,16.0,1.0,16.4,1.0,0.0,0.0,2022,Manchester City,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,9.0,3.0,21.6,0.0,0.0,0.0,2021,Norwich City,0,0
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,8.0,2.0,22.2,1.0,0.0,0.0,2021,Norwich City,0,1
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,9.0,5.0,17.0,0.0,0.0,0.0,2021,Norwich City,0,0
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,11.0,2.0,14.4,0.0,0.0,0.0,2021,Norwich City,0,0
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,9.0,0.0,18.6,0.0,0.0,0.0,2021,Norwich City,0,1

In [20]:
matches["Opp_Code"] = matches["Opponent"].astype("category").cat.codes

In [21]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,SoT,Dist,FK,PK,PKatt,Season,Team,Target,Venue_Code,Opp_Code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,0,0,16
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,4.0,18.5,1.0,0.0,0.0,2022,Manchester City,1,1,14
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,10.0,14.8,0.0,0.0,0.0,2022,Manchester City,1,1,0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,8.0,14.3,0.0,0.0,0.0,2022,Manchester City,1,0,9
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,16.4,1.0,0.0,0.0,2022,Manchester City,0,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,3.0,21.6,0.0,0.0,0.0,2021,Norwich City,0,0,1
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,2.0,22.2,1.0,0.0,0.0,2021,Norwich City,0,1,18
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,5.0,17.0,0.0,0.0,0.0,2021,Norwich City,0,0,9
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,2.0,14.4,0.0,0.0,0.0,2021,Norwich City,0,0,19
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,0.0,18.6,0.0,0.0,0.0,2021,Norwich City,0,1,16

In [22]:
#String replacement and write a regular expression to replace 
#colon and minutes with number
#matches['Hour'] = matches['Time'].split(':')[0]
matches['Hour'] = matches['Time'].str.replace(":.+","", regex=True).astype("int")

In [23]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,Season,Team,Target,Venue_Code,Opp_Code,Hour
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,17.3,1.0,0.0,0.0,2022,Manchester City,0,0,16,16
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,18.5,1.0,0.0,0.0,2022,Manchester City,1,1,14,15
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,14.8,0.0,0.0,0.0,2022,Manchester City,1,1,0,12
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,14.3,0.0,0.0,0.0,2022,Manchester City,1,0,9,15
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,16.4,1.0,0.0,0.0,2022,Manchester City,0,1,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,21.6,0.0,0.0,0.0,2021,Norwich City,0,0,1,15
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,22.2,1.0,0.0,0.0,2021,Norwich City,0,1,18,14
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,17.0,0.0,0.0,0.0,2021,Norwich City,0,0,9,19
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,14.4,0.0,0.0,0.0,2021,Norwich City,0,0,19,14
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,18.6,0.0,0.0,0.0,2021,Norwich City,0,1,16,16

In [24]:
#number for each day of the week (mon is 1, tues is 2)
matches["Day_Code"] = matches["Date"].dt.dayofweek

In [25]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,Target,Venue_Code,Opp_Code,Hour,Day_Code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,0,16,16,6
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,1,14,15,5
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,1,0,12,5
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,1,0,9,15,5
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,0,1,15,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,0.0,0.0,0.0,2021,Norwich City,0,0,1,15,5
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,1.0,0.0,0.0,2021,Norwich City,0,1,18,14,6
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,0.0,0.0,0.0,2021,Norwich City,0,0,9,19,2
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,0.0,0.0,0.0,2021,Norwich City,0,0,19,14,6
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,0.0,0.0,0.0,2021,Norwich City,0,1,16,16,6

In [26]:
#Random Forest picks up non-linearities in the data
#RF is a series of decision trees but each decision tree has slightly diff parameter
from sklearn.ensemble import RandomForestClassifier as RF

In [27]:
#higher the no of estimators is, the longer it will take to run and potentially more accurate it will be
#higher min_samples_split means it's less likely to overfit but lower acc on training data
rf = RF(n_estimators = 50, min_samples_split = 10, random_state = 1)

In [28]:
train_data =  matches[matches['Date'] < '2022-01-01']
test_data = matches[matches['Date'] > '2022-01-01']

In [29]:
predictors = ['Venue_Code', 'Opp_Code', 'Hour', 'Day_Code']

In [30]:
rf.fit(train_data[predictors], train_data["Target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [31]:
preds = rf.predict(test_data[predictors])

In [32]:
from sklearn.metrics import accuracy_score, precision_score

In [33]:
score = accuracy_score(test_data['Target'], preds)

In [34]:
score

0.6056701030927835

In [35]:
#Check accuracy is high vs low by comparing actual and predicted values
combined = pd.DataFrame(dict(actual=test_data['Target'], prediction = preds))

In [36]:
combined

    actual  prediction
31       1           0
32       0           1
34       1           0
35       1           1
37       0           1
..     ...         ...
38       0           0
39       0           0
40       0           0
41       0           1
42       0           0

[776 rows x 2 columns]

In [37]:
#Create crosstab
pd.crosstab(index = combined["actual"], columns = combined['prediction'])

prediction    0    1
actual
0           362  104
1           202  108

In [38]:
#Percentage of time when teama actually won
score = precision_score(test_data['Target'], preds)

In [39]:
score

0.5094339622641509

In [40]:
grouped_matches = matches.groupby('Team')
grouped_matches

In [41]:
#look at a single group
group = grouped_matches.get_group("Manchester City")
group

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,Target,Venue_Code,Opp_Code,Hour,Day_Code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,0,16,16,6
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,1,14,15,5
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,1,0,12,5
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,1,0,9,15,5
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,0,1,15,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2022-04-30,17:30,Premier League,Matchweek 35,Sat,Away,W,4,0,Leeds United,...,0.0,0.0,0.0,2021,Manchester City,1,0,8,17,5
54,2022-05-08,16:30,Premier League,Matchweek 36,Sun,Home,W,5,0,Newcastle Utd,...,1.0,0.0,0.0,2021,Manchester City,1,1,13,16,6
55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5,1,Wolves,...,0.0,0.0,0.0,2021,Manchester City,1,0,19,20,2
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2,2,West Ham,...,2.0,0.0,1.0,2021,Manchester City,0,0,18,14,6
57,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3,2,Aston Villa,...,1.0,0.0,0.0,2021,Manchester City,1,1,1,16,6

In [42]:
def rolling_averages(group, cols, new_cols):
    #sort group by date to be in ascending order for last 3 matches
    group = group.sort_values("Date")
    #compute rolling averages and closed = left takes current week out
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] =  rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [43]:
cols = ['GF','GA','Sh','SoT','Dist','FK','PK','PKatt']
#create new column
new_cols = [f"{c}_rolling" for c in cols]

In [44]:
new_cols

['GF_rolling',
 'GA_rolling',
 'Sh_rolling',
 'SoT_rolling',
 'Dist_rolling',
 'FK_rolling',
 'PK_rolling',
 'PKatt_rolling']

In [45]:
rolling_averages(group, cols, new_cols)

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Hour,Day_Code,GF_rolling,GA_rolling,Sh_rolling,SoT_rolling,Dist_rolling,FK_rolling,PK_rolling,PKatt_rolling
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,15,5,1.666667,0.666667,17.333333,4.000000,17.700000,1.000000,0.0,0.000000
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,12,5,3.333333,0.333333,16.666667,4.000000,18.100000,1.000000,0.0,0.000000
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,12,5,5.000000,0.000000,19.000000,6.000000,17.266667,0.666667,0.0,0.000000
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,15,5,5.000000,0.000000,22.000000,8.000000,16.033333,0.333333,0.0,0.000000
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,15,5,3.666667,0.000000,25.000000,9.333333,14.633333,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5,1,Wolves,...,20,2,5.000000,0.333333,19.000000,7.666667,15.566667,0.666667,0.0,0.000000
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2,2,West Ham,...,14,6,5.000000,0.666667,17.000000,6.333333,15.133333,0.333333,0.0,0.000000
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2,2,West Ham,...,14,6,4.000000,1.333333,20.000000,5.666667,16.000000,0.666667,0.0,0.333333
57,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3,2,Aston Villa,...,16,6,3.000000,1.666667,25.000000,6.333333,17.300000,1.333333,0.0,0.666667
57,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3,2,Aston Villa,...,16,6,2.333333,2.000000,28.000000,6.333333,17.133333,1.666667,0.0,0.666667

In [46]:
#apply to all matches which applies 1 function to each team
matches_rolling = matches.groupby("Team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [47]:
matches_rolling

                                 Date   Time            Comp         Round  \
Team
Arsenal                 1  2021-08-22  16:30  Premier League   Matchweek 2
                        3  2021-08-28  12:30  Premier League   Matchweek 3
                        3  2021-08-28  12:30  Premier League   Matchweek 3
                        4  2021-09-11  15:00  Premier League   Matchweek 4
                        4  2021-09-11  15:00  Premier League   Matchweek 4
...                               ...    ...             ...           ...
Wolverhampton Wanderers 39 2022-05-11  20:15  Premier League  Matchweek 33
                        40 2022-05-15  14:00  Premier League  Matchweek 37
                        40 2022-05-15  14:00  Premier League  Matchweek 37
                        41 2022-05-22  16:00  Premier League  Matchweek 38
                        41 2022-05-22  16:00  Premier League  Matchweek 38

                            Day Venue Result  GF  GA         Opponent  ...  \
Team                                                                   ...
Arsenal                 1   Sun  Home      L   0   2          Chelsea  ...
                        3   Sat  Away      L   0   5  Manchester City  ...
                        3   Sat  Away      L   0   5  Manchester City  ...
                        4   Sat  Home      W   1   0     Norwich City  ...
                        4   Sat  Home      W   1   0     Norwich City  ...
...                         ...   ...    ...  ..  ..              ...  ...
Wolverhampton Wanderers 39  Wed  Home      L   1   5  Manchester City  ...
                        40  Sun  Home      D   1   1     Norwich City  ...
                        40  Sun  Home      D   1   1     Norwich City  ...
                        41  Sun  Away      L   1   3        Liverpool  ...
                        41  Sun  Away      L   1   3        Liverpool  ...

                            Hour  Day_Code  GF_rolling  GA_rolling Sh_rolling  \
Team
Arsenal                 1     16         6    0.000000    2.000000  16.666667
                        3     12         5    0.000000    2.000000  11.333333
                        3     12         5    0.000000    3.000000   4.333333
                        4     15         5    0.000000    4.000000   2.666667
                        4     15         5    0.333333    3.333333  10.666667
...                          ...       ...         ...         ...        ...
Wolverhampton Wanderers 39    20         2    1.666667    3.000000  11.666667
                        40    14         6    1.333333    4.000000   9.333333
                        40    14         6    1.000000    3.666667  10.333333
                        41    16         6    1.000000    2.333333  13.666667
                        41    16         6    1.000000    1.666667  13.666667

                           SoT_rolling Dist_rolling FK_rolling  PK_rolling  \
Team
Arsenal                 1     3.666667    18.900000   0.666667         0.0
                        3     3.333333    18.800000   0.333333         0.0
                        3     2.000000    14.733333   0.000000         0.0
                        4     1.000000    10.766667   0.000000         0.0
                        4     2.000000    10.166667   0.333333         0.0
...                                ...          ...        ...         ...
Wolverhampton Wanderers 39    3.666667    16.033333   0.000000         0.0
                        40    3.333333    16.466667   0.000000         0.0
                        40    3.333333    18.200000   0.333333         0.0
                        41    3.666667    19.500000   0.666667         0.0
                        41    4.333333    18.766667   0.666667         0.0

                            PKatt_rolling
Team
Arsenal                 1             0.0
                        3             0.0
                        3             0.0
                        4             0.0
                        4             0.0
...                                   ...
Wolverhampton Wanderers 39            0.0
                        40            0.0
                        40            0.0
                        41            0.0
                        41            0.0

[1460 rows x 39 columns]

In [48]:
matches_rolling = matches_rolling.droplevel('Team')

In [49]:
matches_rolling

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Hour,Day_Code,GF_rolling,GA_rolling,Sh_rolling,SoT_rolling,Dist_rolling,FK_rolling,PK_rolling,PKatt_rolling
1,2021-08-22,16:30,Premier League,Matchweek 2,Sun,Home,L,0,2,Chelsea,...,16,6,0.000000,2.000000,16.666667,3.666667,18.900000,0.666667,0.0,0.0
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Away,L,0,5,Manchester City,...,12,5,0.000000,2.000000,11.333333,3.333333,18.800000,0.333333,0.0,0.0
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Away,L,0,5,Manchester City,...,12,5,0.000000,3.000000,4.333333,2.000000,14.733333,0.000000,0.0,0.0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1,0,Norwich City,...,15,5,0.000000,4.000000,2.666667,1.000000,10.766667,0.000000,0.0,0.0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1,0,Norwich City,...,15,5,0.333333,3.333333,10.666667,2.000000,10.166667,0.333333,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Home,L,1,5,Manchester City,...,20,2,1.666667,3.000000,11.666667,3.666667,16.033333,0.000000,0.0,0.0
40,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Norwich City,...,14,6,1.333333,4.000000,9.333333,3.333333,16.466667,0.000000,0.0,0.0
40,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Norwich City,...,14,6,1.000000,3.666667,10.333333,3.333333,18.200000,0.333333,0.0,0.0
41,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,Liverpool,...,16,6,1.000000,2.333333,13.666667,3.666667,19.500000,0.666667,0.0,0.0
41,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,Liverpool,...,16,6,1.000000,1.666667,13.666667,4.333333,18.766667,0.666667,0.0,0.0

In [50]:
#Unique values in index
matches_rolling.index = range(matches_rolling.shape[0])

In [51]:
matches_rolling

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Hour,Day_Code,GF_rolling,GA_rolling,Sh_rolling,SoT_rolling,Dist_rolling,FK_rolling,PK_rolling,PKatt_rolling
0,2021-08-22,16:30,Premier League,Matchweek 2,Sun,Home,L,0,2,Chelsea,...,16,6,0.000000,2.000000,16.666667,3.666667,18.900000,0.666667,0.0,0.0
1,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Away,L,0,5,Manchester City,...,12,5,0.000000,2.000000,11.333333,3.333333,18.800000,0.333333,0.0,0.0
2,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Away,L,0,5,Manchester City,...,12,5,0.000000,3.000000,4.333333,2.000000,14.733333,0.000000,0.0,0.0
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1,0,Norwich City,...,15,5,0.000000,4.000000,2.666667,1.000000,10.766667,0.000000,0.0,0.0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1,0,Norwich City,...,15,5,0.333333,3.333333,10.666667,2.000000,10.166667,0.333333,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Home,L,1,5,Manchester City,...,20,2,1.666667,3.000000,11.666667,3.666667,16.033333,0.000000,0.0,0.0
1456,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Norwich City,...,14,6,1.333333,4.000000,9.333333,3.333333,16.466667,0.000000,0.0,0.0
1457,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Norwich City,...,14,6,1.000000,3.666667,10.333333,3.333333,18.200000,0.333333,0.0,0.0
1458,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,Liverpool,...,16,6,1.000000,2.333333,13.666667,3.666667,19.500000,0.666667,0.0,0.0
1459,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,Liverpool,...,16,6,1.000000,1.666667,13.666667,4.333333,18.766667,0.666667,0.0,0.0

In [52]:
def predictions(data, predictors):
    train_data =  data[data['Date'] < '2022-01-01']
    test_data = data[data['Date'] > '2022-01-01']
    rf = RF(n_estimators = 50, min_samples_split = 10, random_state = 1)
    rf.fit(train_data[predictors], train_data["Target"])
    preds = rf.predict(test_data[predictors])
    combined = pd.DataFrame(dict(actual=test_data['Target'], prediction = preds))
    prec_score = precision_score(test_data['Target'], preds)
    return combined, prec_score

In [53]:
#GF_rolling	GA_rolling	Sh_rolling	SoT_rolling	Dist_rolling	FK_rolling	PK_rolling	PKatt_rolling
combined, precision = predictions(matches_rolling, predictors + new_cols)

In [54]:
precision

0.6848484848484848

In [55]:
combined

      actual  prediction
37         0           0
38         0           0
39         1           0
40         1           0
41         1           1
...      ...         ...
1455       0           0
1456       0           0
1457       0           0
1458       0           0
1459       0           0

[776 rows x 2 columns]

In [56]:
#merge based on index for corresponding teams, opp and result
combined = combined.merge(matches_rolling[['Date','Team','Opponent','Result']], 
                          left_index = True, right_index = True)

In [57]:
combined

,actual,prediction,Date,Team,Opponent,Result
37,0,0,2022-01-23,Arsenal,Burnley,D
38,0,0,2022-01-23,Arsenal,Burnley,D
39,1,0,2022-02-10,Arsenal,Wolves,W
40,1,0,2022-02-10,Arsenal,Wolves,W
41,1,1,2022-02-19,Arsenal,Brentford,W
...,...,...,...,...,...,...
1455,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L
1456,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D
1457,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D
1458,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L
1459,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L

In [64]:
#Rename team names in team col to align with names in opp col
class MissingDict(dict):
    #create a class that inherits from the dictionary class for not handling missing keys
    __missing__ = lambda self, key:key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd",
                                   "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", 
                                   "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"}
    #create an instance of MissingDict
mapping = MissingDict(**map_values)

In [65]:
mapping["West Ham United"]

'West Ham'

In [66]:
combined["New_team"] = combined["Team"].map(mapping)

In [67]:
combined

,actual,prediction,Date,Team,Opponent,Result,New_team
37,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
38,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
39,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
40,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
41,1,1,2022-02-19,Arsenal,Brentford,W,Arsenal
...,...,...,...,...,...,...,...
1455,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolves
1456,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves
1457,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves
1458,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves
1459,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves

In [68]:
#merge dataframe with itself for new team and opponent
merged = combined.merge(combined, left_on = ["Date", "New_team"], right_on = ["Date", "Opponent"])
merged

,actual_x,prediction_x,Date,Team_x,Opponent_x,Result_x,New_team_x,actual_y,prediction_y,Team_y,Opponent_y,Result_y,New_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
2,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
3,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
4,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,1,Wolverhampton Wanderers,Arsenal,L,Wolves
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves,0,0,Norwich City,Wolves,D,Norwich City
1548,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool
1549,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool
1550,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool
1551,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool

In [70]:
#to check for rows where one team wins and other loses
merged[(merged["prediction_x"] == 1) & (merged["prediction_y"] == 0)]["actual_x"].value_counts()

1    219
0     77
Name: actual_x, dtype: int64

In [71]:
219/296

0.7398648648648649